# docker image settings, required section
container:
  # Image name to start on worker, required param.
  image: "sonm/eth-claymore@sha256:86f3f53e9631650b3499bc653005997d21d8878db4c545df181f7821fd8470df"
  # Env variables that will be passed to container on start.
  env:
    WALLET: <addr>
    USE_ALLPOOLS: true
    USE_ALLCOINS: true
    # Ethereum mining params
    # POOL: <pool>
    # WORKER: <worker>
    # EMAIL: <email>

    # Pascal mining params.
    # Set address to enable dual mining with PascalCoin
    # PASC_ADDRESS: <addr>
    # PASC_PAYMENTID: 0
